apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nimble-platform
    name: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble-platform
      name: catalog-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: nimble-platform
        name: catalog-service
    spec:
      containers:
      - image: nimbleplatform/catalogue-service-micro-srdc
        imagePullPolicy: Always
        name: catalog-service
        ports:
        - containerPort: 8095
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
          - name: DISCOVERY_ENABLED
            value: "false"

---

kind: Service
metadata:
  name: catalog-service
  labels:
    app: nimble-platform
    name: catalog-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8095
      targetPort: 8095
  selector:
    app: nimble-platform
    name: catalog-service