apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue-service
    name: catalogue-service
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
      name: catalogue-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: catalogue-service
        name: catalogue-service
    spec:
      containers:
#      can be overwritten with "-set spec.template.spec.containers[0].image=image_url"
      - image: nimbleplatform/catalogue-service-micro:test
      - image: nimbleplatform/catalogue-service-micro:IMAGE_TAG
        imagePullPolicy: Always
        name: catalogue-service
        ports:
        - containerPort: 8095
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 512Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
          - name: DISCOVERY_ENABLED
            value: "false"

          # UBL database
          - name: UBL_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: ubl_db_host
          - name: UBL_DB_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: ubl_db_port
          - name: UBL_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: ubl_db_name
          - name: UBL_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: ubl_db_username
          - name: UBL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalogue-service-secret
                key: ubl_db_password

          # SyncDB database
          - name: SYNC_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: sync_db_host
          - name: SYNC_DB_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: sync_db_port
          - name: SYNC_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: sync_db_name
          - name: SYNC_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: sync_db_username
          - name: SYNC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalogue-service-secret
                key: sync_db_password
          - name: CATEGORY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalogue-service-secret
                key: CATEGORY_DB_PASSWORD
          - name: CATEGORY_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: CATEGORY_DB_HOST
          - name: CATEGORY_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: CATEGORY_DB_PORT
          - name: CATEGORY_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: CATEGORY_DB_NAME
          - name: CATEGORY_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: catalogue-service-configmap
                key: CATEGORY_DB_USERNAME
